### ISSUE TITLE
lambda for GRL is minus，but the grad has been reversal before multiply lambda.

### ISSUE THREAD

**Issue by trizh** [CuthbertCai/pytorch_DANN#10]
I found you have set the gamma = -10 in params.py. That means the lambda is always minus, but you have use grad_output = grad_output.neg() in GRL in the code models.py, that means the grad is always positive, which it is different from what the article said.

**Comment by CuthbertCai** [comment]
@trizh Thanks for pointing out this mistake. I think gamma should be 10. I'm not sure whether it is wrong in the first time or is changed after several revisions. I'll correct it and rerun the code.
