### ISSUE TITLE
There is something wrong

### ISSUE THREAD

**Issue by SecNet-mi** [CuthbertCai/pytorch_DANN#17]
When I run the main.py, the error comes :RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

**Comment by xstarfish** [comment]
Me too. Have you solved it now？

**Comment by CuthbertCai** [comment]
> Me too. Have you solved it now？

Could you please give me more details about the error? Generally, all images in different datasets are reshaped into [3, 28, 28] as shown in `models.py`. Also, maybe you can try a older version of pytorch, such as 0.4.1.

**Comment by linagwei** [comment]
> Me too. Have you solved it now？
scipy==1.1.0
numpy==1.14.3
matplotlib==2.1.0
torch==0.4.1
Pillow>=5.1.0
scikit_learn==0.19.2
torchvision==0.2.1

I do not know the reason. However, I fixed this problem. I changed the requirements.txt as above, then run the command
pip install --user -r requirements.txt
Then, this problem was solved.

**Comment by SecNet-mi** [comment]
> Me too. Have you solved it now？

scipy==1.1.0
numpy==1.14.3
matplotlib==2.1.0
torch==0.4.1
Pillow>=5.1.0
scikit_learn==0.19.2
torchvision==0.2.1

I do not know the reason. However, I fixed this problem. I changed the requirements.txt as above, then run the command
pip install --user -r requirements.txt
Then, this problem was solved.

**Comment by xstarfish** [comment]
> > Me too. Have you solved it now？
> 
> Could you please give me more details about the error? Generally, all images in different datasets are reshaped into [3, 28, 28] as shown in `models.py`. Also, maybe you can try a older version of pytorch, such as 0.4.1.

it works, thank you so much

**Comment by xstarfish** [comment]
> > Me too. Have you solved it now？
> 
> scipy==1.1.0
> numpy==1.14.3
> matplotlib==2.1.0
> torch==0.4.1
> Pillow>=5.1.0
> scikit_learn==0.19.2
> torchvision==0.2.1
> 
> I do not know the reason. However, I fixed this problem. I changed the requirements.txt as above, then run the command
> pip install --user -r requirements.txt
> Then, this problem was solved.

Thanks! The problem has been solved.
