### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by amarpazad** [CuthbertCai/pytorch_DANN#7]
I tried to run the code on py2.7 but it keeps giving me an error -
../models/models.py", line 68, in forward
    input = GradReverse.grad_reverse(input, constant)
TypeError: unbound method grad_reverse() must be called with GradReverse instance as first argument (got Variable instance instead)
I tried with some more combinations of versions (py-3.5, torch 0.4.1, etc.), all gave some or the other error.
I suspect it is due to some version issue of some package. It will be very much helpful if you can upload environment.yml file or version details in a req.txt file.

**Comment by CuthbertCai** [comment]
@amarpazad I add the `requirements.txt`. You can try to run the code again.
